<center>
<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/module_1/images/SN_web_lightmode.png" width="300"> 
</center>

<h1>OpenWeather APIs Calls</h1>

Estimated time needed: **40** minutes

## Lab Overview:

In this lab, you will be collecting real-time current and forecasted weather data for cities using the **OpenWeather API**. It can give you current weather data for any location including over 200,000 cities and 5 day forecasts for free (with limited API usage). You just need to use HTTP requests to call those weather APIs and get the weather data.

You will be given instructions to set up a free OpenWeather API account with an API key for authentication. Then, you will be shown, with code examples, how to get the current weather for a given city. After you are familiar with OpenWeather API, you will be asked to get 5-day forecast data for a list of cities.

## Setup OpenWeather API account

You can create an OpenWeather API account [here](https://home.openweathermap.org/users/sign_up?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkRP0321ENSkillsNetwork878-2022-01-01). After your account has been created and verified, you can go to Account -> My API Keys:

<a href="https://cognitiveclass.ai/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkRP0321ENSkillsNetwork878-2022-01-01">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/module_1/images/l2-openweather-apikey.png" width="400" align="center">
</a>

and find your API key here:

<a href="https://cognitiveclass.ai/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkRP0321ENSkillsNetwork878-2022-01-01">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/module_1/images/l2-openweather-apikey-value.png" width="400" align="center">
</a>

Now mark down your generated API key, which will be used to authenticate your HTTP requests to OpenWeather API.

Note that a new API key may take some time to be activated. You may quickly try the following URL using a web browser.

With the `{your_api_key}` URL parameter replaced by your own API key and go to the following URL:

https://api.openweathermap.org/data/2.5/weather?q=Seoul&appid={your_api_key}


until you see some weather data returned (instead of 401 or other error status), similar to the following JSON result:

```
{"coord":{"lon":126.9778,"lat":37.5683},
"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01n"}],
"base":"stations",
"main":{"temp":285.16,"feels_like":284.04,"temp_min":284.15,"temp_max":287.15,"pressure":1020,"humidity":62},
"visibility":10000,
"wind":{"speed":1.03,"deg":220},"clouds":{"all":0},"dt":1617718307,"sys":{"type":1,"id":8105,"country":"KR","sunrise":1617657021,"sunset":1617703103},"timezone":32400,"id":1835848,"name":"Seoul","cod":200}
```

## Coding Practice: Get the current weather data for a city using OpenWeather API

First import `httr` library

In [1]:
# Check if need to install rvest` library
require("httr")

library(httr)

Loading required package: httr

The API base URL to get current weather is https://api.openweathermap.org/data/2.5/weather

In [2]:
# URL for Current Weather API
current_weather_url <- 'https://api.openweathermap.org/data/2.5/weather'

Next, let's create a list to hold URL parameters for current weather API

In [3]:
# need to be replaced by your real API key
your_api_key <- "your_api_key"
# Input `q` is the city name
# Input `appid` is your API KEY, 
# Input `units` are preferred units such as Metric or Imperial
current_query <- list(q = "Seoul", appid = "6afbaf28dd55f06696a60be4999747e8", units="metric")

Now we can make a HTTP request to the current weather API

In [4]:
response <- GET(current_weather_url, query=current_query)

If we check the response type, we can see it is in JSON format

In [5]:
http_type(response)

[1] "application/json"

JSON is an open standard file and data interchange format that uses human-readable text to store and transmit data objects. To read the JSON HTTP response, you can use the `content()` function to parse it as a named list in R.

In [6]:
json_result <- content(response, as="parsed")

If you use the `class()` function, you can see it is a R `List` object

In [7]:
class(json_result)

[1] "list"

Now let's print the JSON result.

In [8]:
json_result

$coord
$coord$lon
[1] 126.9778

$coord$lat
[1] 37.5683


$weather
$weather[[1]]
$weather[[1]]$id
[1] 701

$weather[[1]]$main
[1] "Mist"

$weather[[1]]$description
[1] "mist"

$weather[[1]]$icon
[1] "50d"



$base
[1] "stations"

$main
$main$temp
[1] 26.16

$main$feels_like
[1] 26.16

$main$temp_min
[1] 24.69

$main$temp_max
[1] 26.78

$main$pressure
[1] 1001

$main$humidity
[1] 84


$visibility
[1] 4000

$wind
$wind$speed
[1] 3.09

$wind$deg
[1] 310


$clouds
$clouds$all
[1] 75


$dt
[1] 1688092597

$sys
$sys$type
[1] 1

$sys$id
[1] 8105

$sys$country
[1] "KR"

$sys$sunrise
[1] 1688069615

$sys$sunset
[1] 1688122641


$timezone
[1] 32400

$id
[1] 1835848

$name
[1] "Seoul"

$cod
[1] 200

It contains very detailed weather data about the city of `Seoul`. Feel free to try other cities as well. We need to convert the named list to a data frame so that we can use data frame operations to process the data. Below is a simple example, which you may implement your own way to convert it to a data frame.

In [9]:
# Create some empty vectors to hold data temporarily
weather <- c()
visibility <- c()
temp <- c()
temp_min <- c()
temp_max <- c()
pressure <- c()
humidity <- c()
wind_speed <- c()
wind_deg <- c()

Now assign the values in the `json_result` list into different vectors

In [10]:
# $weather is also a list with one element, its $main element indicates the weather status such as clear or rain
weather <- c(weather, json_result$weather[[1]]$main)
# Get Visibility
visibility <- c(visibility, json_result$visibility)
# Get current temperature 
temp <- c(temp, json_result$main$temp)
# Get min temperature 
temp_min <- c(temp_min, json_result$main$temp_min)
# Get max temperature 
temp_max <- c(temp_max, json_result$main$temp_max)
# Get pressure
pressure <- c(pressure, json_result$main$pressure)
# Get humidity
humidity <- c(humidity, json_result$main$humidity)
# Get wind speed
wind_speed <- c(wind_speed, json_result$wind$speed)
# Get wind direction
wind_deg <- c(wind_deg, json_result$wind$deg)

Combine all vectors as columns of a data frame

In [11]:
# Combine all vectors
weather_data_frame <- data.frame(weather=weather, 
                                 visibility=visibility, 
                                 temp=temp, 
                                 temp_min=temp_min, 
                                 temp_max=temp_max, 
                                 pressure=pressure, 
                                 humidity=humidity, 
                                 wind_speed=wind_speed, 
                                 wind_deg=wind_deg)

In [12]:
# Check the generated data frame
print(weather_data_frame)

  weather visibility  temp temp_min temp_max pressure humidity wind_speed
1    Mist       4000 26.16    24.69    26.78     1001       84       3.09
  wind_deg
1      310

# TASK:  Get 5-day weather forecasts for a list of cities using the OpenWeather API

Now you should be familiar with the usage of OpenWeather API. Next, you need to complete a task to get 5-day weather forecasts for a list of cities

_TODO:_ Write a function to return a data frame containing 5-day weather forecasts for a list of cities

In [13]:
# Create some empty vectors to hold data temporarily

# City name column
city <- c()
# Weather column, rainy or cloudy, etc
weather <- c()
# Sky visibility column
visibility <- c()
# Current temperature column
temp <- c()
# Max temperature column
temp_min <- c()
# Min temperature column
temp_max <- c()
# Pressure column
pressure <- c()
# Humidity column
humidity <- c()
# Wind speed column
wind_speed <- c()
# Wind direction column
wind_deg <- c()
# Forecast timestamp
forecast_datetime <- c()
# Season column
# Note that for season, you can hard code a season value from levels Spring, Summer, Autumn, and Winter based on your current month.
season <- c()

In [75]:
forecast_url <- 'https://api.openweathermap.org/data/2.5/forecast'
# Create query parameters
forecast_query <- list(q = 'Seoul', appid = "6afbaf28dd55f06696a60be4999747e8", units="metric")
# Make HTTP GET call for the given city
json_list = GET(forecast_url, query=forecast_query)
json_list = content(json_list, as='parsed')$list
result = json_list[39]
months <- c("January", "February", "March", "April", "May", "June",
            "July", "August", "September", "October", "November", "December")
month = as.integer(format(as.Date(result[[1]]$dt_txt, format = '%Y-%m-%d'), "%m"))
print(month)
s = months[month]
s

[1] 7

[1] "July"

In [78]:
result

[[1]]
[[1]]$dt
[1] 1688515200

[[1]]$main
[[1]]$main$temp
[1] 21.1

[[1]]$main$feels_like
[1] 21.59

[[1]]$main$temp_min
[1] 21.1

[[1]]$main$temp_max
[1] 21.1

[[1]]$main$pressure
[1] 1005

[[1]]$main$sea_level
[1] 1005

[[1]]$main$grnd_level
[1] 999

[[1]]$main$humidity
[1] 89

[[1]]$main$temp_kf
[1] 0


[[1]]$weather
[[1]]$weather[[1]]
[[1]]$weather[[1]]$id
[1] 500

[[1]]$weather[[1]]$main
[1] "Rain"

[[1]]$weather[[1]]$description
[1] "light rain"

[[1]]$weather[[1]]$icon
[1] "10d"



[[1]]$clouds
[[1]]$clouds$all
[1] 100


[[1]]$wind
[[1]]$wind$speed
[1] 1.25

[[1]]$wind$deg
[1] 79

[[1]]$wind$gust
[1] 2.41


[[1]]$visibility
[1] 10000

[[1]]$pop
[1] 1

[[1]]$rain
[[1]]$rain$`3h`
[1] 2.56


[[1]]$sys
[[1]]$sys$pod
[1] "d"


[[1]]$dt_txt
[1] "2023-07-05 00:00:00"

In [60]:
library(lubridate)

Attaching package: ‘lubridate’


The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union

In [68]:
# Convert the date-time string to a Date object
datetime <- as.Date("2023-07-04 21:00:00", format = '%Y-%d-%m')
# Extract the month
month_value <- format(datetime, "%m")
month_value

ERROR: Error in as.Time("2023-07-04 21:00:00", format = "%H"): could not find function "as.Time"

In [127]:
months <- c("January", "February", "March", "April", "May", "June",
            "July", "August", "September", "October", "November", "December")
# Get forecast data for a given city list
get_weather_forecaset_by_cities <- function(city_names){
    df_list <- list()
    for (city_name in city_names){
        # Forecast API URL
        forecast_url <- 'https://api.openweathermap.org/data/2.5/forecast'
        # Create query parameters
        forecast_query <- list(q = city_name, appid = "6afbaf28dd55f06696a60be4999747e8", units="metric")
        # Make HTTP GET call for the given city
        json_list = GET(forecast_url, query=forecast_query)
        # Note that the 5-day forecast JSON result is a list of lists. You can print the reponse to check the results
        results <- content(json_list, as="parsed")$list
        # Loop the json result
        for(result in results) {
            city <- c(city, city_name)
            weather <- c(weather,result$weather[[1]]$main)
            visibility <- c(visibility, result$visibility)
            temp <- c(temp, result$main$temp)
            temp_min <- c(temp_min, result$main$temp_min)
            temp_max <- c(temp_max, result$main$temp_max)
            pressure <- c(pressure, result$main$pressure)
            humidity <- c(humidity, result$main$humidity)
            wind_speed <- c(wind_speed, result$wind$speed)
            wind_deg <- c(wind_deg, result$wind$deg)
            forecast_datetime <- c(forecast_datetime, result$dt_txt)
            month = as.integer(format(as.Date(result$dt_txt, format = '%Y-%m-%d'), "%m"))
            s = months[month]
            season <- c(season, s)
        }
    }
    data_list <- list(
            city = city,
            weather = weather,
            visibility = visibility,
            temp = temp,
            temp_min = temp_min,
            temp_max = temp_max,
            pressure = pressure,
            humidity = humidity,
            wind_speed = wind_speed,
            wind_deg = wind_deg,
            forecast_datetime = forecast_datetime,
            season = season

        )
    max_length <- max(lengths(data_list))

    # Extend the vectors in the list to match the maximum length using NA values
    data_list <- lapply(data_list, function(x) {
      if (length(x) < max_length) {
        c(x, rep(NA, max_length - length(x)))
      } else {
        x
      }
    })

    # Convert the list to a data frame
    df <- data.frame(data_list)
    
    # Return a data frame
    return(df)
    
}

Complete and call `get_weather_forecaset_by_cities` function with a list of cities, and write the data frame into a csv file called `cities_weather_forecast.csv`

In [129]:
cities <- c("Seoul", "Washington, D.C.", "Paris", "Suzhou")
cities_weather_df <- get_weather_forecaset_by_cities(cities)
cities_weather_df

    city   weather visibility temp  temp_min temp_max pressure humidity
1   Seoul  Rain    10000      26.38 24.53    26.38    1001     82
2   Seoul  Rain    10000      27.26 27.24    27.26    1000     75
3   Seoul  Rain    10000      24.62 24.62    24.62    1001     86
4   Seoul  Rain    10000      23.91 23.91    23.91    1002     89
5   Seoul  Rain    10000      22.96 22.96    22.96    1003     93
6   Seoul  Clouds  10000      22.50 22.50    22.50    1005     93
7   Seoul  Clouds  10000      27.06 27.06    27.06    1006     73
8   Seoul  Clouds  10000      31.70 31.70    31.70    1006     53
9   Seoul  Clouds  10000      32.98 32.98    32.98    1005     46
10  Seoul  Clear   10000      30.69 30.69    30.69    1005     56
11  Seoul  Clear   10000      26.58 26.58    26.58    1007     71
12  Seoul  Clear   10000      24.42 24.42    24.42    1008     80
13  Seoul  Clear   10000      23.30 23.30    23.30    1009     86
14  Seoul  Clear   10000      22.74 22.74    22.74    1009     90
15  Seoul  Clear   10000      26.86 26.86    26.86    1009     70
16  Seoul  Clouds  10000      30.39 30.39    30.39    1009     52
17  Seoul  Clouds  10000      33.04 33.04    33.04    1007     41
18  Seoul  Clear   10000      32.21 32.21    32.21    1006     44
19  Seoul  Clouds  10000      28.80 28.80    28.80    1006     60
20  Seoul  Clouds  10000      27.42 27.42    27.42    1006     67
21  Seoul  Clouds  10000      26.20 26.20    26.20    1004     71
22  Seoul  Clouds  10000      24.52 24.52    24.52    1005     81
23  Seoul  Clouds  10000      29.09 29.09    29.09    1004     57
24  Seoul  Clouds  10000      33.41 33.41    33.41    1003     35
25  Seoul  Clouds  10000      33.42 33.42    33.42    1003     33
26  Seoul  Rain    10000      30.10 30.10    30.10    1003     44
27  Seoul  Rain    10000      27.67 27.67    27.67    1004     52
28  Seoul  Clear   10000      25.66 25.66    25.66    1006     60
29  Seoul  Clouds  10000      24.49 24.49    24.49    1005     64
30  Seoul  Clouds  10000      23.99 23.99    23.99    1004     67
⋮   ⋮      ⋮       ⋮          ⋮     ⋮        ⋮        ⋮        ⋮
135 Suzhou Rain    10000      28.82 28.82    28.82    1005     80
136 Suzhou Rain    10000      28.66 28.66    28.66    1005     83
137 Suzhou Rain    10000      29.15 29.15    29.15    1004     79
138 Suzhou Clouds  10000      28.14 28.14    28.14    1003     84
139 Suzhou Clouds  10000      27.15 27.15    27.15    1004     89
140 Suzhou Rain    10000      26.77 26.77    26.77    1004     92
141 Suzhou Clouds  10000      26.68 26.68    26.68    1002     92
142 Suzhou Clouds  10000      26.80 26.80    26.80    1002     91
143 Suzhou Clouds  10000      27.37 27.37    27.37    1003     89
144 Suzhou Clouds  10000      29.24 29.24    29.24    1003     80
145 Suzhou Rain    10000      29.20 29.20    29.20    1002     80
146 Suzhou Clouds  10000      29.31 29.31    29.31    1002     78
147 Suzhou Clouds  10000      27.95 27.95    27.95    1003     84
148 Suzhou Rain    10000      27.10 27.10    27.10    1003     86
149 Suzhou Rain    10000      26.76 26.76    26.76    1002     87
150 Suzhou Clouds  10000      26.26 26.26    26.26    1002     90
151 Suzhou Rain    10000      28.27 28.27    28.27    1002     81
152 Suzhou Clouds  10000      31.67 31.67    31.67    1002     68
153 Suzhou Clouds  10000      31.53 31.53    31.53    1001     68
154 Suzhou Clouds  10000      30.04 30.04    30.04    1000     75
155 Suzhou Clouds  10000      28.19 28.19    28.19    1001     83
156 Suzhou Rain    10000      27.39 27.39    27.39    1001     86
157 Suzhou Rain    10000      26.67 26.67    26.67    1000     90
158 Suzhou Rain    10000      25.89 25.89    25.89    1001     91
159 Suzhou Rain    10000      25.47 25.47    25.47    1002     91
160 Suzhou Rain    10000      24.47 24.47    24.47    1002     94
161 Suzhou Rain       NA         NA    NA       NA      NA     NA
162 NA     Rain       NA         NA    NA       NA      NA     NA
163 NA     Rain       NA         NA    NA       NA      NA     NA
164 NA     Rain       NA         NA    NA       NA      NA     NA
    wind_speed wind_deg forecast_datetime   season
1   1.48        37      2023-06-30 06:00:00 June
2   1.04        47      2023-06-30 09:00:00 June
3   0.31        46      2023-06-30 12:00:00 June
4   1.16        20      2023-06-30 15:00:00 June
5   0.80        77      2023-06-30 18:00:00 June
6   0.94        41      2023-06-30 21:00:00 June
7   0.31       276      2023-07-01 00:00:00 July
8   1.20       279      2023-07-01 03:00:00 July
9   3.14       277      2023-07-01 06:00:00 July
10  2.52       261      2023-07-01 09:00:00 July
11  1.68       248      2023-07-01 12:00:00 July
12  1.34       244      2023-07-01 15:00:00 July
13  1.11       234      2023-07-01 18:00:00 July
14  0.22       133      2023-07-01 21:00:00 July
15  0.38       176      2023-07-02 00:00:00 July
16  1.64       290      2023-07-02 03:00:00 July
17  2.25       309      2023-07-02 06:00:00 July
18  1.77       323      2023-07-02 09:00:00 July
19  0.93       300      2023-07-02 12:00:00 July
20  0.56       165      2023-07-02 15:00:00 July
21  0.66        36      2023-07-02 18:00:00 July
22  0.85       295      2023-07-02 21:00:00 July
23  2.36        16      2023-07-03 00:00:00 July
24  1.76       146      2023-07-03 03:00:00 July
25  1.96       154      2023-07-03 06:00:00 July
26  1.92       299      2023-07-03 09:00:00 July
27  1.18       288      2023-07-03 12:00:00 July
28  1.59       268      2023-07-03 15:00:00 July
29  0.85       255      2023-07-03 18:00:00 July
30  0.68       166      2023-07-03 21:00:00 July
⋮   ⋮          ⋮        ⋮                   ⋮
135 1.87       155      2023-07-02 00:00:00 July
136 3.52       281      2023-07-02 03:00:00 July
137 3.26       341      2023-07-02 06:00:00 July
138 1.78        55      2023-07-02 09:00:00 July
139 2.90       118      2023-07-02 12:00:00 July
140 2.57       130      2023-07-02 15:00:00 July
141 2.20       171      2023-07-02 18:00:00 July
142 2.24       217      2023-07-02 21:00:00 July
143 2.24       203      2023-07-03 00:00:00 July
144 2.29       243      2023-07-03 03:00:00 July
145 2.03       263      2023-07-03 06:00:00 July
146 2.28       279      2023-07-03 09:00:00 July
147 1.62       308      2023-07-03 12:00:00 July
148 1.23       248      2023-07-03 15:00:00 July
149 1.40       186      2023-07-03 18:00:00 July
150 1.52       163      2023-07-03 21:00:00 July
151 2.13       169      2023-07-04 00:00:00 July
152 2.45       223      2023-07-04 03:00:00 July
153 3.35       265      2023-07-04 06:00:00 July
154 2.71       292      2023-07-04 09:00:00 July
155 2.30       308      2023-07-04 12:00:00 July
156 1.48       317      2023-07-04 15:00:00 July
157 2.67       302      2023-07-04 18:00:00 July
158 2.30       333      2023-07-04 21:00:00 July
159 2.62       310      2023-07-05 00:00:00 July
160 2.61       328      2023-07-05 03:00:00 July
161   NA        NA      NA                  NA
162   NA        NA      NA                  NA
163   NA        NA      NA                  NA
164   NA        NA      NA                  NA

In [130]:
# Write cities_weather_df to `cities_weather_forecast.csv`
write.csv(cities_weather_df, "cities_weather_forecast.csv", row.names=FALSE)

For more details about HTTP requests with `httr`, please refer to the previous HTTP request notebook here: 

[HTTP request in R](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/M4_Working_With_Data/lab2_jupyter_http-request.ipynb)

## TASK: Download datasets as csv files from cloud storage

The last task of this lab is straightforward: download some aggregated datasets from cloud storage

In [131]:
# Download several datasets

# Download some general city information such as name and locations
url <- "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/raw_worldcities.csv"
# download the file
download.file(url, destfile = "raw_worldcities.csv")

# Download a specific hourly Seoul bike sharing demand dataset
url <- "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/raw_seoul_bike_sharing.csv"
# download the file
download.file(url, destfile = "raw_seoul_bike_sharing.csv")

## Next Step

Now you should collect all datasets required for this project, all in csv format. Feel free to explore them preliminarily now. However, they are the raw datasets and have to be processed for further data visualization or data analysis.

In the next module, you will improve their quality by performing data wrangling tasks.

## Authors

<a href="https://www.linkedin.com/in/yan-luo-96288783/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkRP0321ENSkillsNetwork878-2022-01-01" target="_blank">Yan Luo</a>

### Other Contributors

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By | Change Description           |
| ----------------- | ------- | ---------- | ---------------------------- |
| 2021-04-05        | 0.1     | Yan        | Initial version created      |
|                   |         |            |                              |
|                   |         |            |                              |

## <h3 align="center"> © IBM Corporation 2021. All rights reserved. <h3/>